export class Banks {
  banks:any = {
  	SBI:'State Bank of India',
   	HDF:'HDFC Bank',
	ICI:'ICICI Bank',
	AXB:'AXIS Bank',
	CIT:'CITI Bank',
	ALB:'Allahabad Bank',
	ANB:'Andhra Bank',
	BBK:'Bank of Bahrain and Kuwait',
	BOB:'Bank of Baroda',
	BOI:'Bank of India',
	BOM:'Bank of Maharastra',
	CNB:'Canara Bank',
	CSYB:'Catholic Syrian Bank',
	CBI:'Central Bank of India',
	CITU:'City Union Bank',
	CRB:'Corporation Bank',
	DNB:'Dena bank',
	DEUB:'Deutche Bank',
	DECB:'Development Credit Bank',
	ESFB:'Equitas Small Finance Bank',
	FBL:'Federal Bank',
	IDB:'IDBI Bank',
	IDF:'IDFC Bank',
	INB:'Indian Bank',
	IOB:'Indian Overseas Bank',
	IIB:'IndusInd Bank',
	JNKB:'Jammu and Kashmir Bank',
	KTB:'Karnataka Bank Ltd',
	KVB:'Karur Vyasa Bank',
	KOBK:'KOTAK Bank',
	LXCB:'Laxmi Vilas Bank',
	OBC:'Oriental Bank of Commerce',
	PSB:'Punjab and Sind Bank',
	PNB:'Punjab National Bank',
	RBL:'RBL Bank Limited',
	SHVB:'Shamrao Vittal Cooperative Bank',
	SIB:'South Indian Bank',
	STCB:'Standard Chartered Bank',
	SBJ:'State Bank of Bikaner and Jaipur',
	SBH:'State Bank of Hyderabad',
	SBM:'State Bank of Mysore',
	SBP:'State Bank of Patiala',
	SBT:'State Bank of Travancore',
	SYB:'Syndicate Bank',
	TMB:'Tamilnadu Mercentile Bank',
	UCO:'UCO Bank',
	UOB:'Union Bank of India',
	UBI:'United Bank of India',
	VJB:'Vijaya Bank',
	YBL:'YES Bank'}
	
}