export class States{
	
	states:any = {
			AN: "Union Territory of Andaman and Nicobar Islands",
			AP: "Andhra Pradesh",
			AR: "Arunachal Pradesh",
			AS: "Assam",
			BR: "Bihar",
			CH: "Chandigarh",
			CT: "State of Chhattisgarh",
			DD: "Daman and Diu",
			DL: "National Capital Territory of Delhi",
			DN: "Dadra and Nagar Haveli",
			GA: "Goa",
			GJ: "Gujarat",
			HP: "State of Himachal Pradesh",
			HR: "Haryana",
			JH: "State of Jharkhand",
			JK: "Kashmir",
			KA: "Karnataka",
			KL: "Kerala",
			LD: "Laccadives",
			MH: "Maharashtra",
			ML: "Meghalaya",
			MN: "Manipur",
			MP: "Madhya Pradesh",
			MZ: "Mizoram",
			NL: "Nagaland",
			OR: "Odisha",
			PB: "State of Punjab",
			PY: "Union Territory of Puducherry",
			RJ: "Rajasthan",
			SK: "Sikkim",
			TG: "Telangana",
			TN: "Tamil Nadu",
			TR: "Tripura",
			UL: "Uttarakhand",
			UP: "Uttar Pradesh",
			WB: "West Bengal"
			}


	cities:any ={
	
	AN:	["Maru","Port Blair","Sawi"],
	AP:	["Akividu","Amalapuram","Anantapur","Andra","Avanigadda","Bapatla","Bhimavaram","Bobbili"
	    ,"Chirala","Chittoor","Cumbum","Darsi","Dhone","Eluru","Gampalagudem","Gannavaram","Gorantla","Gudivada","Guntur","Kadapa","Kakinada","Kanigiri","Kavali","Kovvur","Kuppam","Kurnool","Machilipatnam","Madanapalle","Mahal","Mandapeta","Mangalagiri","Markapur","Medarametla","Muddanuru","Nagari","Nandigama","Nandyal","Narasaraopet","Nellore","Nuzvid","Ongole","Pakala","Peddapuram","Piduguralla","Pileru","Pithapuram","Proddatur","Puttur","Rajahmundry","Ramapuram","Ramavaram","Singarayakonda","Srikakulam","Tadepallegudem","Tanuku","Thenali","Tirumala","Tirumala - Tirupati","Vijayawada","Vinukonda","Visakhapatnam","Vizianagaram","Yanam"],
	AR:	["Hong","Itanagar"],
	AS:	["Arunachal","Barpeta","Bhandari","Dhubri","Dibrugarh","Golaghat","Goshaingaon","Guwahat","Jorhat","Karimganj","Kokrajhar","Lala","Nalbari","Namrup","Nazira","North Lakhimpur","Powai","Sibsagar","Silchar","Tezpur","Tinsukia","Ulubari"],
	BR: ["Banka","Begusarai","Bhagalpur","Bhawanipur","BiharSharif","Chandan","Darbhanga","Dhaka"
		,"Gaya","Jaynagar","Jha Jha","Kamat","Motihari","Munger","Muzaffarpur","Patna","Purnea","Pusa","Raxaul","Sakri","Samastipur"],
	CH: ["Chandigarh"],
	CT: ["Ambikapur","Bemetara","Bhatapara","Bhilai","Bilaspur","Champa","Dhamtari","Durg","Jagdalpur","Janjgir","Koni","Korba","Kumhari","Lanka","Mohala","Raigarh","Raipur","Sukma"],
	DD: ["Daman"],
	DL: ["Alipur","Bawana","ConnaughtPlace","Delhi","KalkajiDevi","Narela","NewDelhi",
		"Shahdara"],
	DN: ["Amal","Silvassa"],
	GA: ["Aldona","Arpora","Assagao","Bambolim","Betalbatim","Betim","Calangute","Candolim","Caranzalem","Chicalim","Cuncolim","Curchorem","Dicholi","Dona Paula","Goa","Madgaon","Marmagao","Navelim","Panjim","Parra","Ponda","Quepem","Saligao","Sanquelim","Solim","Vainguinim","Vasco","Verna"],
	GJ: ["Ahmedabad","Amreli","Amroli","Anand","Ankleshwar","Antapur","Bardoli","Basu","Bhadath",
		"Bharuch","Bhavnagar","Bhuj","Bilimora","Chhota Udepur","Dahod","Dewan","Dhansura","Dhrol","Dwarka","Gandhidham","Gandhinagar","Ghana","Godhra","Himatnagar","Jalalpur","Jamnagar","Junagadh","Kalol","Karamsad","Keshod","Khambhat","Kheda","Khergam","Kosamba","Mahesana","Malpur","Mandvi","Matar","Mithapur","Modasa","Morvi","Mundra","Nadiad","Nagwa","Navsari","Patan","Petlad","Porbandar","Rajkot","Rander","Rawal","Sachin","Sami","Sanand","Somnath","Surendranagar","Thasra","Vadodara","Vadodra","Valsad","Vapi","Vijapur","Visnagar"],
	HP:	["Bhawan","Bilaspur","Chamba","Dharamsala","Dharmpur","Hamirpur","Hari","Kalka","Kangra","Kumar","Manali","Mandi","Mani","Mashobra","Nalagarh","Nehra","Nurpur","Palampur","Paonta Sahib","Shimla","Solan"],
	HR: ["Ambala","Aurangabad","Bahadurgarh","Ballabgarh","Bhiwani","Budha","Chhachhrauli","Faridabad","Fatehabad","Ganga","Gohana","Gurgaon","Hansi","Haryana","Hisar","Indraprast","Jhajjar","Jind","Kaithal","Kalra","Karnal","Kaul","Kotian","Ladwa","Narnaul","Nilokheri","Odhan","Palwal","Panipat","Pehowa","Rewari","Rohtak","Saha","Shahabad","Sirsa","Sodhi","Sonipat","Tohana","Yamunanagar"],
	JH:	["Bokaro","Dhanbad","Dumka","Hazaribagh","Jamshedpur","Mahulia","Ramgarh","Ranchi"],
	JK: ["Anantnag","Arch","Bala","Bawan","Gold","Jammu","Kargil","Kathua","Katra","Kundan","Markal","Nila","Pahalgam","Patel","Raju","Ranjan","Ring","Srinagar","Suman"],
	KA: ["Bagalkot","Bangalore","Belgaum","Bellare","Bellary","Bhadravati","Bhatkal","Bidar","Bijapur","Channapatna","Chikmagalūr","Chikodi","Chintamani","Chitradurga","Davangere","Dharwad","Gadag","Gulbarga","Hadadi","Hassan","Haveri","Hira","Hiriyur","Honavar","Hospet","Hubli","Karwar","Kolar","Kollegal","Koppal","Kushalnagar","Madikeri","Mandya","Mangalore","Manipala","Mundgod","Mysore","Nandi","Puttur","Raichur","Ramanagaram","Sagar","Sandur","Sangam","Shanti Grama","Shimoga","Sirsi","Siruguppa","Someshwar","Tiptur","Tumkūr","Udupi","Yadgir"],
	KL: ["Alanallur","Alappuzha","Aluva","Anchal","Angadipuram","Aranmula","Attingal","Changanacheri","Chengannur","Chittur","Edavanna","Ernakulam","Guruvayur","Idukki","Irinjalakuda","Kaladi","Kalpetta","Kanhangad","Kannur","Kasaragod","Kayamkulam","Kochi","Kodungallur","Kollam","Koni","Kottakkal","Kottarakara","Kottayam","Kozhikode","Malappuram","Manjeri","Mattanur","Mavelikara","Nilambur","Ottappalam","Palakkad","Palayam","Parappanangadi","Paravur","Pathanamthitta","Pattambi","Payyanur","Ponnani","Punalur","Shoranur","Sultans Battery","Thalassery","Thiruvananthapuram","Thrissur","Tirur","Tiruvalla","Vaikam","Vazhakulam"],
	LD: ["Kavaratti"],
	MH: ["Abdul","Ahmednagar","Akola","Alibag","Ambad","Ambarnath","Amravati","Andheri","Arvi","Aundh","Aurangabad","Badlapur","Bandra","Baramati","Belapur","Bhandup","Bhiwandi","Bhusawal","Boisar","Chakan","Chalisgaon","Chandrapur","Charan","Chinchvad","Chiplun","Chopda","Colaba","Dahanu","Deolali","Devgarh","Dharavi","Dhule","Ellora Caves","Gargoti","Ghatkopar","Goregaon","Hinganghat","Hingoli","Ichalkaranji","Igatpuri","Jalgaon Jamod","Jalna","Kagal","Kalam","Kalamboli","Kalyan","Kankauli","Karad","Karanja","Karjat","Khalapur","Khopoli","Kolhapur","Latur","Mahad","Mahim","Mangaon","Manor","Miraj","Mumbai","Nadgaon","Nagpur","Nanded","Nandurbar","Narayangaon","Nashik","Neral","Neri","Osmanabad","Palghar","Palus","Panchgani","Pandharpur","Panvel","Parbhani","Parel","Pimpri","Pune","Puras","Ratnagiri","Sakri","Sangamner","Sangli","Sangola","Satara","Shahapur","Shirgaon","Shrigonda","Sinnar","Sion","Solapur","Sopara","Talegaon Dabhade","Thane","Trimbak","Tuljapur","Ulhasnagar","Umred","Vadner","Vasai","Vashi","Virar","Wai","Wardha","Yavatmal","Yeola"],
	ML: ["Nongpoh","Nongstoin","Pala","Shillong","Tura"],
	MN: ["Churachandpur","Imphal"],
	MP: ["Amarkantak","Ambah","Anantpur","Bagh","Balaghat","Baroda","Berasia","Betul","Bhagwan","Bhartiya","Bhopal","Chakra","Chand","Chhindwara","Chopra","Damoh","Dewas","Dhar","Dindori","Gandhigram","Ganpat","Guna","Gwalior","Hoshangabad","Indore","Jabalpur","Kailaras","Kamalpura","Kataria","Katni","Khajuraho Group of Monuments","Khargone","Mandla","Mandsaur","Mhow","Morena","Nadia","Nagara","Pachmarhi","Raipur","Rajapur","Rama","Ratlam","Rewa","Sagar","Sarangi","Satna","Sehore","Sendhwa","Shahdol","Sidhi","Soni","Tala","Ujjain","Vidisha"],
	MZ: ["Aizawl"],
	NL: ["Chen","Dimapur","Kohima"],
	OR: ["Angul","Balangir","Balasore","Bargarh","Barpali","Bhubaneswar","Brahmapur","Cuttack","Dhenkanal","Jajpur","Jatani","Jaypur","Jharsuguda","Kalinga","Khurda","Koraput","Nayagarh","Puri","Raurkela","Rayagada","Sambalpur","Sundargarh","Talcher","Udaigiri"],
	PB:	["Amritsar","Banga","Barnala","Batala","Bhatinda","Dasua","Dhariwal","Dhuri","Dinanagar","Faridkot","Firozpur","Garhshankar","Gurdaspur","Hoshiarpur","Jagraon","Jalalabad","Jalandhar","Kapurthala Town","Khanna","Kharar","Kot Isa Khan","Kurali","Ludhiana","Machhiwara","Maharaj","Mansa","Moga","Mohali","Morinda","Mukerian","Muktsar","Nabha","Pathankot","Patiala","Phagwara","Rajpura","Rupnagar","Sangrur","Shahkot","Sirhind","Sunam","Talwandi Sabo","Tarn Taran"],
	PY:	["Karaikal","Puducherry"],
	RJ: ["Ajmer","Alwar","Amer","Amet","Balana","Bali","Banswara","Barmer","Beawar","Bharatpur","Bhilwara","Bikaner","Binavas","Bundi","Charu","Chetan","Chhabra","Dipas","Ganganagar","Gangapur","Gangrar","Jaipur","Jaisalmer","Jhalawar","Jhunjhunun","Jodhpur","Kalan","Kanakpura","Khan","Khinwara","Kishangarh","Kolayat","Kota","Lamba Harisingh","Mahajan","Mahatma","Mandal","Manna","Mount Abu","Nagar","Nagaur","Nanda","Naraina","Nathdwara","Pali","Pilani","Pitampura","Pushkar","Rana","Roshan","Shiv","Sikar","Sirohi","Sojat","Sultan","Surana","Suratgarh","Thali","Tonk","Udaipur"],
	SK: ["Gangtok","Manu","Singtam","Sirwani"],
	TG: ["Adilabad","Balanagar","Bhongir","Bodhan","Gudur","Hyderabad","Karimnagar","Khammam","Kottagudem","Mancherial","Medak","Medchal","Nalgonda","Narsapur","Nizamabad","Paloncha","Patancheru","Patelguda","Pochampalli","Secunderabad","Shadnagar","Suriapet","Uppal","Vikarabad","Warangal"],
	TN: ["Alangulam","Ambur","Annamalainagar","Arakkonam","Arani","Ariyalur","Attur","Bodinayakkanur","Chennai","Cheyyar","Chidambaram","Choolai","Coimbatore","Coonoor","Cuddalore","Devipattinam","Dharapuram","Dharmapuri","Dindigul","Ekkattuthangal","Eral","Erode","Fort","Gobichettipalayam","Guindy","Hosur","Kalpakkam","Kanchipuram","Kangayam","Kaniyambadi","Kanniyakumari","Karaikudi","Karamadai","Karur","Kodaikanal","Koothanallur","Kovilpatti","Krishnagiri","Kumbakonam","Kuzhithurai","Lalgudi","Madurai","Madurantakam","Mahabalipuram","Mannargudi","Mettur","Mylapore","Nagapattinam","Nagercoil","Namakkal","Neyveli","Omalur","Ooty","Palani","Palladam","Panruti","Pattukkottai","Perambalur","Peranampattu","Perundurai","Pollachi","Ponneri","Pudukkottai","Puliyur","Rajapalaiyam","Ramanathapuram","Ranippettai","Salem","Sattur","Sholavandan","Sirkazhi","Siruseri","Sivaganga","Sivakasi","Sriperumbudur","Srirangam","Srivilliputhur","Tambaram","Thanjavur","Thenkasi","Thirumangalam","Thiruthani","Thiruvarur","Thoothukudi","Tindivanam","Tiruchchendur","Tiruchi","Tirunelveli","Tiruppur","Tiruvallur","Tiruvannamalai","Turaiyur","Vadamadurai","Vandalur","Vandavasi","Vaniyambadi","Vellore","Villupuram","Wellington","Yercaud"],
	TR: ["Agartala","Kamalpur"],
	UL: ["Adwani","Almora","Dang","Dangi","Dehradun","Dhanaulti","Dogadda","Dwarahat","Haldwani",
		"Haridwar","Jamal","Jaspur","Kashipur","Lohaghat","Mill","Mussoorie","Nagal","Naini","Pantnagar","Pauri","Pithoragarh","Ramnagar","Rishikesh","Roorkee","Sidhpur","Uttarkashi","Vikasnagar"],
	UP: ["Agra","Ajabpur","Aligarh","Allahabad","Anandnagar","Arora","Azamgarh","Bagpat","Balu","Banda","Bank","Bareilly","Basti","Bela","Bhadohi","Bichpuri","Budaun","Bulandshahr","Chandauli","Chandausi","Chitra","Dadri","Dasna","Deoria","Etawah","Faizabad","Fatehgarh","Fatehpur","Firozabad","Ghaziabad","Gonda","Gorakhpur","Hamirpur","Hapur","Iglas","Jalesar","Jaunpur","Jhansi","Kaimganj","Kanpur","Karari","Kasganj","Kasia","Khandar","Khatauli","Kheri","Khurja","Kunwar","Lakhimpur","Lucknow","Madhoganj","Mathan","Mathura","Mawana","Meerut","Mehra","Mirza Murad","Mirzapur","Mohan","Moradabad","Muzaffarnagar","Noida","Orai","Padrauna","Phaphamau","Pilkhuwa","Potti","Rampur","Saharanpur","Sahibabad","Shahjahanpur","Shamsabad","Sikka","Sitapur","Sultanpur","Tanda","Teri","Tikamgarh","Unnao","Varanasi"],
	WB: ["Alipur","Asansol","Baharampur","Baidyabati","Bali","Balurghat","Bangaon","Bankura","Barakpur","Barddhaman","Basirhat","Behala","Belgharia","Binnaguri","Bishnupur","Bolpur","Budbud","Canning","Chandannagar","Dam Dam","Darjeeling","Durgapur","Farakka","Ghatal","Gujrat","Habra","Haldia","Haripur","Howrah","Hugli","Jadabpur","Jalpaiguri","Jayanti","Jhargram","Kakdwip","Kalyani","Kanchrapara","Kandi","Karsiyang","Katoya","Kharagpur","Koch Bihar","Kolkata","Konnagar","Kulti","Liluah","Maldah","Manipur","Mayapur","Medinipur","Multi","Murshidabad","Nabadwip","Panchal","Puruliya","Rajpur","Ranaghat","Raniganj","Rudrapur","Rupnarayanpur","Salt Lake City","Saranga","Serampore","Shyamnagar","Siliguri","Siuri"]
	}
}
